# Data Analytics 3 (Naive Bayes)

### 1. Implement Naive Bayes using Python/R to perform classificationon iris.csv dataset.
### 2. Compute Confusion matrix to find TP,FP,TN,FN,Accuracy, Error rate, Precision, Recall on the given dataset

In [1]:
# Import the libraries

import numpy as np
import pandas as pd

In [3]:
# Load the dataset

dataframe = pd.read_csv('Iris.csv')
print(dataframe.info())
print(dataframe.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [4]:
# Check unique values in the Species column

print(dataframe['Species'].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [5]:
# Remove the Id column

dataframe = dataframe.drop('Id', axis=1)

In [11]:
# Label encode the Species column

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dataframe['Species'] = le.fit_transform(dataframe['Species'])

# The Species column is now label encoded as 0, 1, and 2(0 for Iris-setosa, 1 for Iris-versicolor, and 2 for Iris-virginica)


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [12]:
X = dataframe.drop('Species', axis=1)
y = dataframe['Species']

# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
# Train the model using Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [15]:
# Predict the Species of the test set
y_pred = model.predict(X_test)

print(y_pred)

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [18]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

# Calculate the accuracy of the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
0.9666666666666667
